[project]
name = "stealth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "logging>=0.4.9.6",
    "serpapi>=0.1.5",
    "fastapi>=0.110.0",
    "uvicorn>=0.22.0",
    "google-genai>=1.24.0",
]
